name: Publish image to Docker Hub
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t bugzapper/iss-app-cicd:latest

      - uses: actions/checkout@v3
      - name: Push
        run: | 
          docker login -u undefined0x@protonmail.com -p ${{ secrets.DOCKER_HUB_TOKEN }} 
          docker push bugzapper/iss-app-cicd:latest







