name: Publish image to Docker Hub
on:
  [workflow-dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t bugzapper/iss-app-cicd:latest
      - name: | 
          docker push bugzapper/iss-app-cicd:latest
